# Generated by Django 3.0 on 2020-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200701_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
